// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexAlytics.Infrastructure.Data;

#nullable disable

namespace NexAlytics.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260228052858_FixStgVentaDecimal")]
    partial class FixStgVentaDecimal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NexAlytics.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "juan@example.com",
                            EmpresaId = 1,
                            FechaRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Juan Pérez",
                            Telefono = "555-1001"
                        },
                        new
                        {
                            Id = 2,
                            Email = "maria@example.com",
                            EmpresaId = 1,
                            FechaRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "María García",
                            Telefono = "555-1002"
                        },
                        new
                        {
                            Id = 3,
                            Email = "carlos@example.com",
                            EmpresaId = 1,
                            FechaRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Carlos López",
                            Telefono = "555-1003"
                        });
                });

            modelBuilder.Entity("NexAlytics.Domain.Entities.DataWarehouse.DimCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DimClientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClienteId = 1,
                            EmpresaId = 1,
                            Nombre = "Juan Pérez"
                        },
                        new
                        {
                            Id = 2,
                            ClienteId = 2,
                            EmpresaId = 1,
                            Nombre = "María García"
                        },
                        new
                        {
                            Id = 3,
                            ClienteId = 3,
                            EmpresaId = 1,
                            Nombre = "Carlos López"
                        });
                });

            modelBuilder.Entity("NexAlytics.Domain.Entities.DataWarehouse.DimFecha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Año")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<string>("NombreMes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Trimestre")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DimFechas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Año = 2025,
                            Fecha = new DateTime(2025, 12, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Mes = 12,
                            NombreMes = "Diciembre",
                            Trimestre = 4
                        },
                        new
                        {
                            Id = 2,
                            Año = 2025,
                            Fecha = new DateTime(2025, 12, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Mes = 12,
                            NombreMes = "Diciembre",
                            Trimestre = 4
                        },
                        new
                        {
                            Id = 3,
                            Año = 2026,
                            Fecha = new DateTime(2025, 12, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Mes = 1,
                            NombreMes = "Enero",
                            Trimestre = 1
                        },
                        new
                        {
                            Id = 4,
                            Año = 2026,
                            Fecha = new DateTime(2025, 12, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Mes = 1,
                            NombreMes = "Enero",
                            Trimestre = 1
                        });
                });

            modelBuilder.Entity("NexAlytics.Domain.Entities.DataWarehouse.DimProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DimProductos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = "Electrónica",
                            EmpresaId = 1,
                            Nombre = "Laptop Pro",
                            ProductoId = 1
                        },
                        new
                        {
                            Id = 2,
                            Categoria = "Periféricos",
                            EmpresaId = 1,
                            Nombre = "Mouse Inalámbrico",
                            ProductoId = 2
                        },
                        new
                        {
                            Id = 3,
                            Categoria = "Electrónica",
                            EmpresaId = 1,
                            Nombre = "Monitor 27\"",
                            ProductoId = 3
                        });
                });

            modelBuilder.Entity("NexAlytics.Domain.Entities.DataWarehouse.FactPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int>("FechaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PagoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FechaId");

                    b.ToTable("FactPagos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmpresaId = 1,
                            FechaId = 1,
                            Monto = 1329.98m,
                            PagoId = 1
                        },
                        new
                        {
                            Id = 2,
                            EmpresaId = 1,
                            FechaId = 2,
                            Monto = 399.99m,
                            PagoId = 2
                        },
                        new
                        {
                            Id = 3,
                            EmpresaId = 1,
                            FechaId = 4,
                            Monto = 29.99m,
                            PagoId = 3
                        });
                });

            modelBuilder.Entity("NexAlytics.Domain.Entities.DataWarehouse.FactVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("ClienteDimId")
                        .HasColumnType("int");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int>("FechaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VentaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteDimId");

                    b.HasIndex("FechaId");

                    b.ToTable("FactVentas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidad = 1,
                            ClienteDimId = 1,
                            EmpresaId = 1,
                            FechaId = 1,
                            Total = 1329.98m,
                            VentaId = 1
                        },
                        new
                        {
                            Id = 2,
                            Cantidad = 1,
                            ClienteDimId = 2,
                            EmpresaId = 1,
                            FechaId = 2,
                            Total = 399.99m,
                            VentaId = 2
                        },
                        new
                        {
                            Id = 3,
                            Cantidad = 1,
                            ClienteDimId = 3,
                            EmpresaId = 1,
                            FechaId = 3,
                            Total = 1299.99m,
                            VentaId = 3
                        },
                        new
                        {
                            Id = 4,
                            Cantidad = 1,
                            ClienteDimId = 1,
                            EmpresaId = 1,
                            FechaId = 4,
                            Total = 29.99m,
                            VentaId = 4
                        });
                });

            modelBuilder.Entity("NexAlytics.Domain.Entities.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Empresas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Empresa Demo S.A."
                        });
                });

            modelBuilder.Entity("NexAlytics.Domain.Entities.ImportJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArchivoNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Registros")
                        .HasColumnType("int");

                    b.Property<int>("RegistrosError")
                        .HasColumnType("int");

                    b.Property<int>("RegistrosProcesados")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("ImportJobs");
                });

            modelBuilder.Entity("NexAlytics.Domain.Entities.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VentaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VentaId");

                    b.ToTable("Pagos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Fecha = new DateTime(2025, 12, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Metodo = "Tarjeta",
                            Monto = 1329.98m,
                            VentaId = 1
                        },
                        new
                        {
                            Id = 2,
                            Fecha = new DateTime(2025, 12, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Metodo = "Transferencia",
                            Monto = 399.99m,
                            VentaId = 2
                        },
                        new
                        {
                            Id = 3,
                            Fecha = new DateTime(2025, 12, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Metodo = "Efectivo",
                            Monto = 29.99m,
                            VentaId = 4
                        });
                });

            modelBuilder.Entity("NexAlytics.Domain.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Categoria = "Electrónica",
                            EmpresaId = 1,
                            Nombre = "Laptop Pro",
                            Precio = 1299.99m
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Categoria = "Periféricos",
                            EmpresaId = 1,
                            Nombre = "Mouse Inalámbrico",
                            Precio = 29.99m
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Categoria = "Electrónica",
                            EmpresaId = 1,
                            Nombre = "Monitor 27\"",
                            Precio = 399.99m
                        });
                });

            modelBuilder.Entity("NexAlytics.Domain.Entities.Staging.StgCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ImportJobId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Procesado")
                        .HasColumnType("bit");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StgClientes");
                });

            modelBuilder.Entity("NexAlytics.Domain.Entities.Staging.StgProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ImportJobId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Precio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Procesado")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("StgProductos");
                });

            modelBuilder.Entity("NexAlytics.Domain.Entities.Staging.StgVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClienteNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fecha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ImportJobId")
                        .HasColumnType("int");

                    b.Property<bool>("Procesado")
                        .HasColumnType("bit");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("StgVentas");
                });

            modelBuilder.Entity("NexAlytics.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmpresaId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@demo.com",
                            EmpresaId = 1,
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Administrador",
                            PasswordHash = "240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9",
                            Rol = "Admin"
                        });
                });

            modelBuilder.Entity("NexAlytics.Domain.Entities.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Ventas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClienteId = 1,
                            EmpresaId = 1,
                            Estado = "Completada",
                            Fecha = new DateTime(2025, 12, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Total = 1329.98m
                        },
                        new
                        {
                            Id = 2,
                            ClienteId = 2,
                            EmpresaId = 1,
                            Estado = "Completada",
                            Fecha = new DateTime(2025, 12, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Total = 399.99m
                        },
                        new
                        {
                            Id = 3,
                            ClienteId = 3,
                            EmpresaId = 1,
                            Estado = "Pendiente",
                            Fecha = new DateTime(2025, 12, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Total = 1299.99m
                        },
                        new
                        {
                            Id = 4,
                            ClienteId = 1,
                            EmpresaId = 1,
                            Estado = "Completada",
                            Fecha = new DateTime(2025, 12, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Total = 29.99m
                        });
                });

            modelBuilder.Entity("NexAlytics.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("NexAlytics.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Clientes")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("NexAlytics.Domain.Entities.DataWarehouse.FactPago", b =>
                {
                    b.HasOne("NexAlytics.Domain.Entities.DataWarehouse.DimFecha", "DimFecha")
                        .WithMany()
                        .HasForeignKey("FechaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DimFecha");
                });

            modelBuilder.Entity("NexAlytics.Domain.Entities.DataWarehouse.FactVenta", b =>
                {
                    b.HasOne("NexAlytics.Domain.Entities.DataWarehouse.DimCliente", "DimCliente")
                        .WithMany()
                        .HasForeignKey("ClienteDimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexAlytics.Domain.Entities.DataWarehouse.DimFecha", "DimFecha")
                        .WithMany()
                        .HasForeignKey("FechaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DimCliente");

                    b.Navigation("DimFecha");
                });

            modelBuilder.Entity("NexAlytics.Domain.Entities.ImportJob", b =>
                {
                    b.HasOne("NexAlytics.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("NexAlytics.Domain.Entities.Pago", b =>
                {
                    b.HasOne("NexAlytics.Domain.Entities.Venta", "Venta")
                        .WithMany("Pagos")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("NexAlytics.Domain.Entities.Producto", b =>
                {
                    b.HasOne("NexAlytics.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Productos")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("NexAlytics.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("NexAlytics.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Usuarios")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("NexAlytics.Domain.Entities.Venta", b =>
                {
                    b.HasOne("NexAlytics.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Ventas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexAlytics.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Ventas")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("NexAlytics.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("NexAlytics.Domain.Entities.Empresa", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("Productos");

                    b.Navigation("Usuarios");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("NexAlytics.Domain.Entities.Venta", b =>
                {
                    b.Navigation("Pagos");
                });
#pragma warning restore 612, 618
        }
    }
}
